# Generated by Django 4.0.1 on 2022-03-03 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("accounts", "0008_alter_asset_content_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="amount",
            field=models.DecimalField(decimal_places=10, default="1", max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="asset",
            name="date_added",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="user",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="asset",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    models.Q(("app_label", "api_data"), ("model", "cryptocurrency")),
                    models.Q(("app_label", "api_data"), ("model", "currency")),
                    models.Q(("app_label", "api_data"), ("model", "metal")),
                    _connector="OR",
                ),
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
