# Generated by Django 4.0.1 on 2022-03-03 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_asset_amount_asset_date_added_asset_user_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="asset",
            old_name="object_id",
            new_name="object_name",
        ),
    ]
