# Generated by Django 4.0.1 on 2022-03-03 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_rename_object_id_asset_object_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="asset",
            old_name="object_name",
            new_name="object_id",
        ),
    ]
