# Generated by Django 4.0.1 on 2022-03-03 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_rename_object_name_asset_object_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="asset",
            old_name="object_id",
            new_name="object_name",
        ),
    ]
