# Generated by Django 4.0.1 on 2022-03-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_rename_object_id_asset_object_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="object_name",
            field=models.CharField(max_length=200),
        ),
    ]
