# Generated by Django 4.0.1 on 2022-03-03 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_remove_asset_object_name_asset_object_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Asset",
        ),
    ]
