# Generated by Django 4.0.1 on 2022-03-19 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_alter_userprofile_selected_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="goal_amount",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
