# Generated by Django 4.0.1 on 2022-03-19 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_data", "0009_rename_metals_metal"),
        ("accounts", "0018_userprofile_goal_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="goal_currency",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goal_currency",
                to="api_data.currency",
            ),
        ),
    ]
