# Generated by Django 4.0.1 on 2022-04-29 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('longitude', models.FloatField(blank=True, default='')),
                ('latitude', models.FloatField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('offer_link', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('price', models.FloatField()),
                ('meters', models.FloatField()),
                ('longitude', models.FloatField(blank=True, default='')),
                ('latitude', models.FloatField(blank=True, default='')),
                ('added_date', models.DateField()),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.city')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('property_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.propertyoffer')),
            ],
        ),
    ]
