# Generated by Django 4.0.1 on 2022-04-29 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyoffer',
            name='website',
            field=models.CharField(choices=[('olx', 'olx'), ('otodom', 'otodom')], default='olx', max_length=50),
            preserve_default=False,
        ),
    ]
