# Generated by Django 4.0.1 on 2022-04-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_propertyoffer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyoffer',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='propertyoffer',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertyoffer',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
