# Generated by Django 4.0.1 on 2022-04-30 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_propertyoffer_active_propertyoffer_favorite_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PropertyPhoto',
            new_name='PropertyImage',
        ),
    ]
