# Generated by Django 4.0.1 on 2022-04-30 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_rename_propertyphoto_propertyimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Searches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=300)),
                ('website', models.CharField(choices=[('olx', 'olx'), ('otodom', 'otodom')], max_length=50)),
                ('max_price', models.IntegerField(null=True)),
                ('min_price', models.IntegerField(null=True)),
                ('distance', models.CharField(choices=[(2, 2), (5, 5), (10, 10), (15, 15), (30, 30), (50, 50), (75, 75), (100, 100)], max_length=4)),
                ('category', models.CharField(choices=[('mieszkania/sprzedaz', 'mieszkania/sprzedaz')], max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='property_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.propertyoffer'),
        ),
    ]
