# Generated by Django 4.0.1 on 2022-05-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_searches_city_alter_searches_distance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyoffer',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='city',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertyoffer',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertyoffer',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='searches',
            name='category',
            field=models.CharField(choices=[('nieruchomosci/mieszkania/sprzedaz', 'nieruchomosci/mieszkania/sprzedaz')], max_length=100),
        ),
    ]
