# Generated by Django 4.0.1 on 2022-03-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cryptocurrency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField(auto_now=True)),
            ],
        ),
    ]
