# Generated by Django 4.0.1 on 2022-03-02 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cryptocurrency",
            name="symbol",
            field=models.CharField(default="a", max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cryptocurrency",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
