# Generated by Django 4.0.1 on 2022-03-02 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_data", "0002_cryptocurrency_symbol_alter_cryptocurrency_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cryptocurrency",
            name="date",
        ),
        migrations.AddField(
            model_name="cryptocurrency",
            name="date_update",
            field=models.CharField(default="a", max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
