# Generated by Django 4.0.1 on 2022-03-02 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_data", "0003_remove_cryptocurrency_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cryptocurrency",
            name="date_update",
        ),
    ]
