# Generated by Django 4.0.1 on 2022-03-02 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_data", "0005_cryptocurrency_date_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cryptocurrency",
            name="date_update",
            field=models.DateTimeField(null=True),
        ),
    ]
