# Generated by Django 4.0.1 on 2022-03-02 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_data", "0006_alter_cryptocurrency_date_update"),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=200, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_update", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="cryptocurrency",
            name="date_update",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
