# Generated by Django 4.0.1 on 2022-03-03 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_data", "0008_metals_alter_currency_price"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Metals",
            new_name="Metal",
        ),
    ]
