# Generated by Django 4.0.1 on 2022-03-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0003_asset"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="operation",
            options={"ordering": ["-operation_date"]},
        ),
        migrations.AddField(
            model_name="operation",
            name="operation_currency",
            field=models.CharField(
                choices=[("PLN", "PLN"), ("USD", "USD"), ("EUR", "EUR")],
                default="PLN",
                max_length=6,
            ),
        ),
        migrations.AddField(
            model_name="operation",
            name="statistic_count",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="operation",
            name="operation_date",
            field=models.DateField(blank=True),
        ),
    ]
